name: 'rust-thanks-action'
description: 'Generate a card from Rust Thanks'
author: 'Yuki Okushi'
branding:
  icon: 'award'
  color: 'green'
inputs:
  github_token:
    required: false
    default: ${{ github.token }}
    description: 'GitHub token'
  name:
    required: true
    description: 'A name listed in Rust Thanks'
  type:
    required: false
    description: 'Whether a card or badge'
    default: 'badge'
  image_url:
    required: false
    description: 'An image URL to be used in a card'
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
