name: 'rust-thanks-action'
description: 'Generate a card from Rust Thanks'
author: 'Yuki Okushi'
inputs:
  name:
    required: true
    description: 'A name listed in Rust Thanks'
runs:
  using: 'node16'
  main: 'dist/index.js'
