name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v2
      - run: |
          pnpm install --frozen-lockfile
          pnpm all
